apiVersion: v1
kind: Service
metadata:
  name: mongodb2-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 27019
    targetPort: 27017
  selector:
    app: mongodb2
  type: LoadBalancer
---