apiVersion: v1
kind: Service
metadata:
  name: mongodb1-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 27018
    targetPort: 27017
  selector:
    app: mongodb1
  type: LoadBalancer
---