apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb0-pvc
spec:
  storageClassName: local-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: mongodb0-pv
  resources:
    requests:
      storage: 1Gi
---