apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  azurestorageaccountname: <your base64 encoded azure storage account name>
  azurestorageaccountkey: <your base64 encoded azure storage account key>
---