apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <your azure aks cluster resource group name>
  name: azure-load-balancer
spec:
  loadBalancerIP: <your azure public ip address> # Must be standard if AKS LoadBalancer is standard, basic if AKS LoadBalancer is basic
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: LoadBalancer
---