apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: LoadBalancer
---